version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: NORGY
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer: # Optional: Web UI for MySQL
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
