services:
  - name: backend-service
    type: web
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_URL
        value: "mysql://avnadmin:AVNS_eioRXQZnw4-lHYLEz74@mysql-3d4fa9f7-norgy.j.aivencloud.com:16785/defaultdb?ssl-mode=REQUIRED"
      - key: PORT
        value: "5000"